### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by RavenHursT** [koajs/static#60]
I have a gulp task that uses webpack to package up my client-side code and puts it into the file `[app_root]/build/public/bundle.js`

My Koa server is also babel transpiled and then placed into `[app_root]/build/index.js`

Then I'm trying the following in my app:

```javascript

import staticServe from 'koa-static'
import koa from 'koa'

let app = koa()

app.use(staticServe('public'))

```

And I keep getting the following error whenever I try to load my page and it tries to request the `bundle.js` file:

```
  BadRequestError: Invalid Request
  .
  .
  at Object.serve (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/koa-static/index.js:41:14)
```

For the time being, I've gotten things to work with the following, but it's obviously a hack and breaks koa's handling of 404's for requests to the `/public` folder, giving me `TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined`...

```javascript
app.use(function* (next) {
  if (this.request.path.indexOf('/public') === 0) {
    yield staticServe(`${__dirname}`)
  } else {
    yield next
  }
})
```

Please help?

**Comment by coderhaoxin** [comment]
GET `/bundle.js`
NOT `/public/bundle.js`

**Comment by RavenHursT** [comment]
Ahhhh

Let me give that a go!

**Comment by RavenHursT** [comment]
Arg.. no go.. I changed my reference in my page to try to grab `/bundle.js` and then tried `app.use(staticServe('public'))` and `app.use(staticServe('./public'))` and still got the same results as the OP in both cases :-(

**Comment by RavenHursT** [comment]
@coderhaoxin I also have the following right below my static routing.  Starting to wonder if the "catch-all" route is mucking things up:

``` javascript
app.use(router.get(`/(.*)`, function* (){
  //does stuff
}))
```

**Comment by coderhaoxin** [comment]
@RavenHursT try `DEBUG=koa-send* node your-app.js` to print the debug info.

**Comment by RavenHursT** [comment]
@coderhaoxin ok.. so this is what I got:

```
<-- GET /
  koa-send send "/" {"root":"/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/public","index":"index.html"} +0ms
--> GET / 200 21ms 127b
  <-- GET /bundle.js
  koa-send send "/bundle.js" {"root":"/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/public","index":"index.html"} +30ms

  BadRequestError: Invalid Request
      at Object.module.exports.throw (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/koala/node_modules/koa/lib/context.js:89:23)
      at Object.callee$0$0$ (/source/index.js:46:17)
      at tryCatch (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at Object.<anonymous> (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/koa-route/index.js:34:19)
      at [object Generator].next (native)
      at Object.serve (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/koa-static/index.js:41:14)
      at [object Generator].next (native)
      at onFulfilled (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/koala/node_modules/koa/node_modules/co/index.js:65:19)
      at run (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:90:39)
      at /Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:101:28
      at flush (/Users/mmarcus/WebstormProjects/Fanatics-3C/3c-middleware/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
      at doNTCallback0 (node.js:407:9)
      at process._tickCallback (node.js:336:13)

  --> GET /bundle.js 400 22ms 856b
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 3ms 4.05kb
```

Still not sure how to tell why this isn't working...

**Comment by RavenHursT** [comment]
@coderhaoxin any idea what's going on here?

**Comment by coderhaoxin** [comment]
Closed due to inactivity!

**Comment by RavenHursT** [comment]
Guess I'll just tackle this myself then...
