### ISSUE TITLE
Get Warning with promise

### ISSUE THREAD

**Issue by farodin91** [koajs/static#62]
Code
```javascript
app.use(koa_static('./dist/', { index: 'index.html' }));
```

```
Warning: a promise was created in a  handler but was not returned from it
    at Object.eval (eval at <anonymous> (/home/farodin/Git/backend/node_modules/thenify/index.js:30:15), <anonymous>:9:8)
    at Object.<anonymous> (/home/farodin/Git/backend/node_modules/koa-send/index.js:72:28)
    at next (native)
    at onFulfilled (/home/farodin/Git/backend/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.then (/home/farodin/Git/backend/node_modules/sequelize/lib/promise.js:21:17)
    at next (/home/farodin/Git/backend/node_modules/co/index.js:100:51)
    at onFulfilled (/home/farodin/Git/backend/node_modules/co/index.js:69:7)
    at /home/farodin/Git/backend/node_modules/co/index.js:54:5
    at Object.co (/home/farodin/Git/backend/node_modules/co/index.js:50:10)
    at Object.toPromise (/home/farodin/Git/backend/node_modules/co/index.js:118:63)
    at next (/home/farodin/Git/backend/node_modules/co/index.js:99:29)
    at onFulfilled (/home/farodin/Git/backend/node_modules/co/index.js:69:7)
    at /home/farodin/Git/backend/node_modules/co/index.js:54:5
    at Object.co (/home/farodin/Git/backend/node_modules/co/index.js:50:10)
    at Object.toPromise (/home/farodin/Git/backend/node_modules/co/index.js:118:63)
    at next (/home/farodin/Git/backend/node_modules/co/index.js:99:29)
    at onFulfilled (/home/farodin/Git/backend/node_modules/co/index.js:69:7)
    at process._tickCallback (node.js:379:9)
```

**Comment by coderhaoxin** [comment]
It seems like some problems with `sequelize`

**Comment by coderhaoxin** [comment]
Maybe same to https://github.com/koajs/koa/issues/607

**Comment by mikestopcontinues** [comment]
@coderhaoxin similar to, anyway. Mongoose seems to be the issue there. I'm getting the same issue with koa2 and koa-convert, like this:

```javascript
app.use(convert(koa_static('deploy')));
```

It's not sequelize. It's in this chain co -> raw-body -> bluebird.

```
Warning: a promise was created in a  handler but was not returned from it
    at Object.eval (eval at <anonymous> (/Users/msc/Sites/msc.com/node_modules/thenify/index.js:30:15), <anonymous>:9:8)
    at Object.<anonymous> (/Users/msc/Sites/msc.com/node_modules/koa-send/index.js:72:28)
    at [object Generator].next (native)
    at onFulfilled (/Users/msc/Sites/msc.com/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at next (/Users/msc/Sites/msc.com/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/msc/Sites/msc.com/node_modules/co/index.js:69:7)
    at /Users/msc/Sites/msc.com/node_modules/co/index.js:54:5
    at new Promise (/Users/msc/Sites/msc.com/node_modules/core-js/modules/es6.promise.js:197:7)
    at Object.co (/Users/msc/Sites/msc.com/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/msc/Sites/msc.com/node_modules/co/index.js:118:63)
    at next (/Users/msc/Sites/msc.com/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/msc/Sites/msc.com/node_modules/co/index.js:69:7)
    at /Users/msc/Sites/msc.com/node_modules/co/index.js:54:5
    at new Promise (/Users/msc/Sites/msc.com/node_modules/core-js/modules/es6.promise.js:197:7)
    at Object.co (/Users/msc/Sites/msc.com/node_modules/co/index.js:50:10)
    at converted (/Users/msc/Sites/msc.com/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/msc/Sites/msc.com/node_modules/koa-compose/index.js:41:32)
    at next (/Users/msc/Sites/msc.com/node_modules/koa-compose/index.js:42:18)
    at createGenerator (/Users/msc/Sites/msc.com/node_modules/koa-convert/index.js:24:16)
    at [object Generator].next (native)
    at Object.compress (/Users/msc/Sites/msc.com/node_modules/koa-compress/index.js:42:12)
    at [object Generator].next (native)
    at onFulfilled (/Users/msc/Sites/msc.com/node_modules/co/index.js:65:19)
```

**Comment by burtonjc** [comment]
@mikestopcontinues and @coderhaoxin I am running into this exact same thing. I tracked it down to an issue in `co`. I opened up tj/co#256 to fix it.

**Comment by mikestopcontinues** [comment]
@burtonjc thanks! It might already be taken care of. With the most recent versions, I no longer have the problem.
